name: propainter-gpu
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - intel-openmp=2023.1.0
  - khronos-opencl-icd-loader=2024.05.08
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libffi=3.4.4
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libuv=1.48.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2025b
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - addict==2.4.0
      - av==14.4.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.18.0
      - fonttools==4.58.0
      - fsspec==2025.5.1
      - future==1.0.0
      - huggingface-hub==0.32.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - tifffile==2025.5.10
      - timm==1.0.15
      - tomli==2.2.1
      - torch==2.7.0
      - torchvision==0.17.2+cu121
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - urllib3==2.4.0
      - yapf==0.43.0
